### ISSUE TITLE
Add Support to PHPStorm 2021.2

### ISSUE THREAD

**Issue by AviMoto** [SysBind/moodle-dev#28]
Add Support to PHPStorm 2021.2

**Comment by luukverhoeven** [comment]
![image](https://user-images.githubusercontent.com/995760/127833269-8dbccc9f-1ec7-4f5e-99dd-f4a3c14a6f06.png)

Is there an estimation when this plugin supports PHPstorm 2021.2?

**Comment by AviMoto** [comment]
Hi @luukverhoeven,
It's take a few days to plugin to be approved by JetBrain team,
Can you approved that this isuue was solved?

**Comment by luukverhoeven** [comment]
👍 Yes, thanks, next day I was able to update .
