### ISSUE TITLE
Add Support for 2022.3

### ISSUE THREAD

**Issue by PhMemmel** [SysBind/moodle-dev#42]
Unfortunately, plugin is currently not working for PHPStorm 2022.3.*, because it is not declared to be compatible with these version of PHPStorm.

When trying to build an own zip file from the repository, I unfortunately get a build error.

Would be nice to have this plugin available for current PHPStorm versions. TIA!

**Comment by AviMoto** [comment]
Hi @PhMemmel ,
We are working on Mid version that will support PHPStorm 2022.3, Some changes are that the plugin is no more alow to change the oriinal PHP files template and we need to implimant it.
We will glade to any kind of help if you can. and hope to enable it ASAP

**Comment by PhMemmel** [comment]
Thank you very much for answering. I just raised this because it looked like the issue is just about interchanging some version numbers and re-release it which apparently is not the case, thank you for clarifying. Unfortunately I will not be able to provide any help here, because I have no experience developing JetBrains plugins at all, sorry :-( But I appreciate your efforts very much, thank you for your great work!
